version: '3.8'
services:
  api:
    build: ./backend
    container_name: api_backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - ./backend/node_modules
  client:
    build: ./web
    container_name: client_react
    ports:
      - '3000:3000'
    volumes:
      - ./web:/app
      - ./app/node_modules
    stdin_open: true
    tty: true